version: '3.8'

services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    volumes:
      - /hdd-data:/share
    ports:
      - "139:139"
      - "445:445"
    environment:
      USER: "${USER};${PASSWORD}"
      SHARE: "Toshiba;/share;yes;no;no;pi"
      TZ: "Europe/Madrid"
      USERID: 1000
      GROUPID: 1000
