version: '3.8'

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      WEBUI_PORT: 80
    volumes:
      - ./config:/config
      - /hdd-data/Descargas:/downloads
    networks:
      - proxied
    restart: unless-stopped

networks:
  proxied:
    external: true