version: "3.8"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=5001
    volumes:
      - ./config:/config
      - /hdd-data/Descargas:/downloads
    ports:
      - 5001:5001
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
