version: '3.8'

services:
  privatebin:
    image: privatebin/nginx-fpm-alpine
    container_name: privatebin
    networks:
      - proxied
    restart: unless-stopped

networks:
  proxied:
    external: true