services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    networks:
      - proxied
    volumes:
      - /hdd-data:/srv
      - ./database.db:/database.db
    user: 1000:1000
    restart: unless-stopped

networks:
  proxied:
    external: true
