version: '3.3'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - /hdd-data:/srv
      - ./database.db:/database.db
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "5000:80"
    restart: on-failure

