version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - proxied
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx:/etc/nginx/
      - /ssl:/ssl
    restart: unless-stopped

networks:
  proxied:
    external: true