version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: host
    volumes:
      - ${PWD}/www:/usr/share/nginx/html
      - ${PWD}/nginx:/etc/nginx/
      - /ssl:/ssl
    restart: unless-stopped
