services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - proxied
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/sites-enabled:/etc/nginx/sites-enabled
      - ./conf/sites-available:/etc/nginx/sites-available
      - /ssl:/ssl
    restart: unless-stopped

networks:
  proxied:
    external: true