services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./users.yml:/data/users.yml:ro
    networks:
      - proxied
    environment:
      DOZZLE_AUTH_PROVIDER: simple
    restart: unless-stopped

networks:
  proxied:
    external: true
