version: '3.8'

services:
  minecraft-server:
    image: itzg/minecraft-server:java17
    container_name: minecraft
    environment:
      TYPE: PAPER
      VERSION: 1.20.1
      EULA: "TRUE"
    volumes:
      - ./server:/data
    ports:
      - 25565:25565
    restart: unless-stopped
    stdin_open: true
    tty: true
    user: 1000:1000
