version: '3.8'

services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    networks:
      - proxied
    volumes:
      - /hdd-data/docker/ytd/downloads:/downloads

networks:
  proxied:
    external: true