services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: raspberry
    networks:
      - proxied
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - ./sync:/var/syncthing
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

networks:
  proxied:
    external: true
