version: '3.8'

services:
  db:
    image: mysql
    restart: always
    container_name: mysql 
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Madrid
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - "3306:3306"
        
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1 
